>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/__init__.py'
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/basic_plotting_example.py'
/Users/houghton/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)
vensim dll not found, vensim functionality not available
/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:892: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
[INFO] results loaded succesfully from ./data/1000 flu cases.tar.gz
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/basic_plotting_example.py", line 22, in <module>
    # we can access each of the axes and make changes
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/ema_workbench/analysis/plotting.py", line 128, in envelopes
    ax = figure.add_subplot(grid[i,0])
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 73, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 508, in __init__
    self._init_axis()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 571, in _init_axis
    self.spines['right'].register_axis(self.yaxis)
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/spines.py", line 163, in register_axis
    self.axis.cla()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axis.py", line 742, in cla
    self.reset_ticks()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axis.py", line 757, in reset_ticks
    self.minorTicks.extend([self._get_tick(major=False)])
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axis.py", line 2000, in _get_tick
    return YTick(self.axes, 0, '', major=major, **tick_kw)
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axis.py", line 150, in __init__
    self.tick1line = self._get_tick1line()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/axis.py", line 538, in _get_tick1line
    zorder=self._zorder)
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/lines.py", line 338, in __init__
    self._marker = MarkerStyle()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/markers.py", line 172, in __init__
    self.set_fillstyle(fillstyle)
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/markers.py", line 222, in set_fillstyle
    self._recache()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/markers.py", line 185, in _recache
    self._path = Path(np.empty((0, 2)))
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/path.py", line 162, in __init__
    self._update_values()
  File "/Users/houghton/anaconda/lib/python2.7/site-packages/matplotlib/path.py", line 214, in _update_values
    rcParams['path.simplify'] and
KeyboardInterrupt
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/cart_flu_example.py'
[INFO] results loaded succesfully from ./data/1000 flu cases.tar.gz
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/cart_flu_example.py", line 44, in <module>
    
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/ema_workbench/analysis/cart.py", line 60, in setup_cart
    y = classify(results[1])
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/cart_flu_example.py", line 21, in classify
    #if deceased population is higher then 1.000.000 people, classify as 1
NameError: global name 'np' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/clustering_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/clustering_example.py", line 19, in <module>
    # specify the number of desired clusters
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/ema_workbench/util/utilities.py", line 62, in load_results
    with tarfile.open(file_name, 'r:gz', encoding="UTF8") as z:
  File "/Users/houghton/anaconda/lib/python2.7/tarfile.py", line 1691, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/Users/houghton/anaconda/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/Users/houghton/anaconda/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '..\\examples\\100 flu cases no policy.cPickle'
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/excel_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/excel_example.py", line 24, in <module>
    uncertainties = [ParameterUncertainty((0.01, 0.2),
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/excel_example.py", line 26, in ExcelModel
    ParameterUncertainty((450,550),
NameError: name 'ParameterUncertainty' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_example.py", line 31, in <module>
    uncertainties = [ParameterUncertainty((0, 0.5), "x11"), #k1
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_example.py", line 33, in MexicanFlu
    ParameterUncertainty((0.0001, 0.1), "x21"), #k3
NameError: name 'ParameterUncertainty' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_pairsplot.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_pairsplot.py", line 19, in <module>
    # transform the results to the required format
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/ema_workbench/util/utilities.py", line 62, in load_results
    with tarfile.open(file_name, 'r:gz', encoding="UTF8") as z:
  File "/Users/houghton/anaconda/lib/python2.7/tarfile.py", line 1691, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/Users/houghton/anaconda/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/Users/houghton/anaconda/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '.\\data\\1000 flu cases no policy.tar.gz'
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_vensim_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_vensim_example.py", line 18, in <module>
    #base case model
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_vensim_example.py", line 24, in FluModel
    
NameError: name 'Outcome' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_vensim_no_policy_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_vensim_no_policy_example.py", line 20, in <module>
    model_file = r'\FLUvensimV1basecase.vpm'
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/flu_vensim_no_policy_example.py", line 25, in FluModel
    
NameError: name 'Outcome' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/lookup_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/lookup_example.py", line 23, in <module>
    outcomes = [Outcome('Accomplishments to Date', time=True),
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/lookup_example.py", line 25, in Burnout
    Outcome('Hours Worked Per Week', time=True),
NameError: name 'Outcome' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/model_debugger.py'
rainfall
adaptation time from non irrigated agriculture
salt effect multiplier
adaptation time to non irrigated agriculture
adaptation time to irrigated agriculture
water shortage multiplier
delay time salt seepage
adaptation time
births multiplier
diffusion lookup
salinity effect multiplier
technological developments in irrigation
adaptation time from irrigated agriculture
food shortage multiplier
deaths multiplier
{'rainfall': '0.154705633188', 'adaptation time from non irrigated agriculture': '0.915157119079', 'salt effect multiplier': '1.11965969891', 'adaptation time to non irrigated agriculture': '0.48434342934', 'adaptation time to irrigated agriculture': '0.330990830832', 'water shortage multiplier': '0.984356102036', 'delay time salt seepage': '6.0', 'adaptation time': '6.90258192256', 'births multiplier': '1.14344734715', 'diffusion lookup': '[(0, 8.0), (10, 8.0), (20, 8.0), (30, 8.0), (40, 7.9999999999999005), (50, 4.0), (60, 9.982194802803703e-14), (70, 1.2455526635140464e-27), (80, 1.5541686655435471e-41), (90, 1.9392517969836692e-55)]', 'salinity effect multiplier': '1.10500381093', 'technological developments in irrigation': '0.0117979353255', 'adaptation time from irrigated agriculture': '1.58060947607', 'food shortage multiplier': '0.955325345996', 'deaths multiplier': '0.875605669911'}
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/model_debugger.py", line 61, in <module>
    elements = line.split("=")
IOError: [Errno 2] No such file or directory: 'C:\\workspace\\EMA-workbench\\models\\salinization\\Verzilting_aanpassingen incorrect.mdl'
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/netlogo_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/netlogo_example.py", line 19, in <module>
    
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/netlogo_example.py", line 24, in PredatorPrey
    ParameterUncertainty((1, 250), "initial-number-wolves"),
NameError: name 'ParameterUncertainty' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/prim_flu_example.py'
[INFO] results loaded succesfully from ./data/1000 flu cases.tar.gz
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/prim_flu_example.py", line 54, in <module>
    box_1 = prim_obj.find_box()
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/ema_workbench/analysis/prim.py", line 689, in setup_prim
    y = classify(results[1])
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/prim_flu_example.py", line 31, in classify
    #if deceased population is higher then 1.000.000 people, classify as 1
NameError: global name 'np' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/prim_wcm_example.py'
[INFO] results loaded succesfully from ./data/5000 runs WCM.tar.gz
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/prim_wcm_example.py", line 35, in <module>
    # let's find a first box
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/ema_workbench/analysis/prim.py", line 689, in setup_prim
    y = classify(results[1])
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/prim_wcm_example.py", line 25, in classify
    classes = np.zeros(outcome.shape[0])
NameError: global name 'default_flow' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/python_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 36, in run_exectests
    fname, 'exec')
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/python_example.py", line 11
    
SyntaxError: from __future__ imports must occur at the beginning of the file
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/scarcity_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 36, in run_exectests
    fname, 'exec')
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/scarcity_example.py", line 9
    
SyntaxError: from __future__ imports must occur at the beginning of the file
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 57, in <module>
    
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 27, in run_exectests
    test_files.sort()
NameError: name 'glob' is not defined
>> Executing '/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/vensim_example.py'
Traceback (most recent call last):
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/test_examples.py", line 37, in run_exectests
    exec(code, {'__name__':'__main__'}, {})
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/vensim_example.py", line 18, in <module>
    example of the most simple case of doing EMA on
  File "/Users/houghton/Google_Drive/Academic Projects/PYSD/EMAworkbench/examples/vensim_example.py", line 29, in VensimExampleModel
    #specify your uncertainties
NameError: name 'Outcome' is not defined
